---
name: 产品购买
about: 购买AI智能体产品
title: '购买 - [产品名称]'
labels:
  - purchase
  - verification
---

## 购买信息

### 购买产品
- [ ] AI智能体团队搭建完整指南（USDT 25）
- [ ] 信息差套利实战手册（USDT 20）
- [ ] 两份产品（USDT 40）

### 支付信息
- **支付金额**: [填写USDT金额]
- **交易哈希**: [填写Tx Hash]
- **付款地址**: [填写你的钱包地址]

### 交付信息
- **GitHub用户名**: [填写你的GitHub用户名，用于邀请到Private Repo]
- **邮箱（可选）**: [用于接收购买确认邮件]

## 重要提示

1. 请确保使用TRC20网络
2. 交易哈希是验证的唯一凭证
3. 验证通过后1-2小时内发送邀请
4. 请确保GitHub用户名正确

## 备注
[其他需要说明的内容]
